apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: pullrequest
spec:
  pipelineSpec:
    tasks:
      - name: from-build-pack
        resources: {}
        taskSpec:
          metadata: {}
          stepTemplate:
            image: uses:y-tree-limited/pipeline-catalog/tasks/gradle-ms-java17/pullrequest.yaml@versionStream
            name: ""
            resources:
              requests:
                cpu: 400m
                memory: 512Mi
            workingDir: /workspace/source
          steps:
            - image: uses:y-tree-limited/pipeline-catalog/tasks/git-clone/git-clone-pr.yaml@versionStream
              name: ""
              resources: {}
            - name: jx-variables
              resources: {}
            - name: build-gradle-ms
              resources: {}
            - name: check-registry
              resources: {}
            - name: build-container-build
              resources: {}
            # - name: promote-jx-preview
            #   resources: {}
  podTemplate:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: node.kubernetes.io/component
              operator: In
              values:
              - "builder"
    tolerations:
    - key: "component"
      operator: "Equal"
      value: "builder"
      effect: "NoSchedule"   
  serviceAccountName: tekton-bot
  timeout: 1h0m0s
status: {}
